---
- hosts: web
  become: yes
  tasks:
   - name:
     replace:
      path: /etc/apache2/apache2.conf
      regexp: "^ServerAdmin.*$"
      replace: "ServerAdmin cloud_user@localhost"
      backup: yes
     notify: "restart web servers"
  handlers:
  - name: for restarting service
    service: 
     name: https
     state: restarted
    listen: "restart web serve"
    
